import { Season, Keyword, Notification } from '@/lib/types/database';

export const SEASONS_DATA: Omit<Season, 'created_by' | 'created_at'>[] = [
    {
        id: 'super-bowl',
        name: 'Super Bowl',
        emoji: '🏈',
        event_date: '02-09',
        color: '#1E3A5F',
        reminder_months_before: 3,
        tips: 'Tập trung vào party supplies, đồ trang trí football, và phụ kiện game day. Sản phẩm cần ready trước 2 tuần event.',
        is_active: true,
    },
    {
        id: 'valentines-day',
        name: "Valentine's Day",
        emoji: '💝',
        event_date: '02-14',
        color: '#E11D48',
        reminder_months_before: 3,
        tips: 'Focus vào quà romantic, trang sức, personalized items. Gifts for her/him là keyword hot nhất.',
        is_active: true,
    },
    {
        id: 'st-patricks-day',
        name: "St. Patrick's Day",
        emoji: '☘️',
        event_date: '03-17',
        color: '#16A34A',
        reminder_months_before: 3,
        tips: 'Green-themed products bán rất tốt. Tập trung vào apparel, party supplies, và Irish-themed gifts.',
        is_active: true,
    },
    {
        id: 'easter',
        name: 'Easter',
        emoji: '🐣',
        event_date: '04-20',
        color: '#A855F7',
        reminder_months_before: 3,
        tips: 'Easter baskets, egg hunt supplies, spring home decor. Pastel colors là trend chính.',
        is_active: true,
    },
    {
        id: 'mothers-day',
        name: "Mother's Day",
        emoji: '👩',
        event_date: '05-11',
        color: '#EC4899',
        reminder_months_before: 3,
        tips: 'Personalized gifts cho mẹ luôn bán chạy. Jewelry, spa sets, kitchen gadgets là top sellers.',
        is_active: true,
    },
    {
        id: 'fathers-day',
        name: "Father's Day",
        emoji: '👨',
        event_date: '06-15',
        color: '#2563EB',
        reminder_months_before: 3,
        tips: 'Tools, BBQ accessories, golf gear, fishing equipment. Dad jokes mugs cũng bán tốt.',
        is_active: true,
    },
    {
        id: 'independence-day',
        name: 'Independence Day',
        emoji: '🇺🇸',
        event_date: '07-04',
        color: '#DC2626',
        reminder_months_before: 3,
        tips: 'Red-white-blue everything! Patriotic decor, flags, outdoor party supplies, fireworks accessories.',
        is_active: true,
    },
    {
        id: 'back-to-school',
        name: 'Back to School',
        emoji: '🎒',
        event_date: '08-01',
        color: '#F59E0B',
        reminder_months_before: 3,
        tips: 'School supplies, backpacks, lunch boxes, dorm room decor. Teacher gifts cũng rất tốt.',
        is_active: true,
    },
    {
        id: 'halloween',
        name: 'Halloween',
        emoji: '🎃',
        event_date: '10-31',
        color: '#EA580C',
        reminder_months_before: 3,
        tips: 'Costumes, spooky decor, trick-or-treat bags, party supplies. Bắt đầu research từ tháng 7.',
        is_active: true,
    },
    {
        id: 'thanksgiving',
        name: 'Thanksgiving',
        emoji: '🦃',
        event_date: '11-27',
        color: '#B45309',
        reminder_months_before: 3,
        tips: 'Fall decor, tablecloth, grateful signs, kitchen items. Harvest theme rất phổ biến.',
        is_active: true,
    },
    {
        id: 'black-friday',
        name: 'Black Friday / Cyber Monday',
        emoji: '💰',
        event_date: '11-28',
        color: '#1F2937',
        reminder_months_before: 3,
        tips: 'Bundle deals, gift sets, trending products. Cần chuẩn bị inventory sớm.',
        is_active: true,
    },
    {
        id: 'christmas',
        name: 'Christmas',
        emoji: '🎄',
        event_date: '12-25',
        color: '#15803D',
        reminder_months_before: 3,
        tips: 'Christmas decor, stocking stuffers, ugly sweaters, gift wrapping. Mùa lớn nhất năm!',
        is_active: true,
    },
];

export const KEYWORDS_DATA: Record<string, Omit<Keyword, 'id' | 'added_by' | 'created_at'>[]> = {
    'super-bowl': [
        { season_id: 'super-bowl', keyword: 'super bowl party supplies', reference_url: 'https://amazon.com', search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'super-bowl', keyword: 'football decor', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'super-bowl', keyword: 'game day snack trays', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'super-bowl', keyword: 'team jerseys', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'super-bowl', keyword: 'tailgate supplies', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'valentines-day': [
        { season_id: 'valentines-day', keyword: 'valentine gifts for her', reference_url: 'https://amazon.com', search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'valentines-day', keyword: 'romantic gifts', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'valentines-day', keyword: 'heart shaped gifts', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'valentines-day', keyword: 'couples gifts', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'valentines-day', keyword: 'personalized valentine', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'valentines-day', keyword: 'rose bear', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'valentines-day', keyword: 'love necklace', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'st-patricks-day': [
        { season_id: 'st-patricks-day', keyword: 'st patricks day shirt', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'st-patricks-day', keyword: 'shamrock decor', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'st-patricks-day', keyword: 'green party supplies', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'st-patricks-day', keyword: 'irish gifts', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'st-patricks-day', keyword: 'leprechaun costume', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'st-patricks-day', keyword: 'clover jewelry', reference_url: null, search_volume: 'Low', competition: 'Low', notes: null },
    ],
    'easter': [
        { season_id: 'easter', keyword: 'easter basket', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'easter', keyword: 'easter egg hunt supplies', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'easter', keyword: 'spring wreath', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'easter', keyword: 'easter bunny decor', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'easter', keyword: 'pastel decor', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
    ],
    'mothers-day': [
        { season_id: 'mothers-day', keyword: 'mothers day gifts', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'mothers-day', keyword: 'mom necklace', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'mothers-day', keyword: 'spa gift set', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'mothers-day', keyword: 'personalized mom gifts', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'mothers-day', keyword: 'mom jewelry', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'fathers-day': [
        { season_id: 'fathers-day', keyword: 'fathers day gifts', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'fathers-day', keyword: 'dad tools', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'fathers-day', keyword: 'bbq gifts', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'fathers-day', keyword: 'golf accessories', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'fathers-day', keyword: 'fishing gifts', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
    ],
    'independence-day': [
        { season_id: 'independence-day', keyword: '4th of july decor', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'independence-day', keyword: 'patriotic shirts', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'independence-day', keyword: 'american flag accessories', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'independence-day', keyword: 'fireworks party', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'independence-day', keyword: 'red white blue', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'back-to-school': [
        { season_id: 'back-to-school', keyword: 'school supplies', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'back-to-school', keyword: 'backpacks', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'back-to-school', keyword: 'lunch boxes', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'back-to-school', keyword: 'teacher gifts', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'back-to-school', keyword: 'dorm room decor', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'halloween': [
        { season_id: 'halloween', keyword: 'halloween costume', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'halloween', keyword: 'spooky decor', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'halloween', keyword: 'trick or treat bags', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'halloween', keyword: 'halloween party supplies', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'halloween', keyword: 'pumpkin decor', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'thanksgiving': [
        { season_id: 'thanksgiving', keyword: 'thanksgiving decor', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'thanksgiving', keyword: 'fall wreath', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'thanksgiving', keyword: 'thanksgiving tablecloth', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
        { season_id: 'thanksgiving', keyword: 'grateful signs', reference_url: null, search_volume: 'Low', competition: 'Low', notes: null },
        { season_id: 'thanksgiving', keyword: 'harvest decor', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
    ],
    'black-friday': [
        { season_id: 'black-friday', keyword: 'deals', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'black-friday', keyword: 'gift bundles', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'black-friday', keyword: 'best sellers', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'black-friday', keyword: 'trending products', reference_url: null, search_volume: 'Medium', competition: 'Medium', notes: null },
        { season_id: 'black-friday', keyword: 'holiday gift sets', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
    ],
    'christmas': [
        { season_id: 'christmas', keyword: 'christmas gifts', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'christmas', keyword: 'christmas tree decor', reference_url: null, search_volume: 'High', competition: 'High', notes: null },
        { season_id: 'christmas', keyword: 'stocking stuffers', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'christmas', keyword: 'ugly christmas sweater', reference_url: null, search_volume: 'High', competition: 'Medium', notes: null },
        { season_id: 'christmas', keyword: 'gift wrapping', reference_url: null, search_volume: 'Medium', competition: 'Low', notes: null },
    ],
};

export const URGENCY_COLORS = {
    critical: { bg: '#FEE2E2', text: '#DC2626', label: 'Khẩn cấp' },
    warning: { bg: '#FFF7ED', text: '#EA580C', label: 'Cần chú ý' },
    attention: { bg: '#FEFCE8', text: '#CA8A04', label: 'Chuẩn bị' },
    safe: { bg: '#F0FDF4', text: '#16A34A', label: 'Thoải mái' },
};

export const STATUS_OPTIONS = [
    { value: 'not_started', label: 'Chưa bắt đầu', color: '#9CA3AF' },
    { value: 'researching', label: 'Đang nghiên cứu', color: '#3B82F6' },
    { value: 'developing', label: 'Đang phát triển', color: '#F59E0B' },
    { value: 'ready', label: 'Sẵn sàng', color: '#10B981' },
    { value: 'launched', label: 'Đã launch', color: '#8B5CF6' },
];

export const NAV_ITEMS = [
    { href: '/', label: 'Dashboard', icon: 'LayoutDashboard' },
    { href: '/calendar', label: 'Calendar', icon: 'Calendar' },
    { href: '/notifications', label: 'Thông báo', icon: 'Bell' },
    { href: '/focus', label: 'Focus', icon: 'Timer' },
    { href: '/settings', label: 'Cài đặt', icon: 'Settings' },
];
